const periodictabledata =
[
    {
        name: "Hydrogen",
        atomicnumber: 1,
        symbol: "H",
        category: "Reactive nonmetal",
        atomicweight: "1.008",
        atomicweightfull: "[1.00784, 1.00811]",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 1,
        period: 1,
        block: "s",

        electronconfig: "1s1",
        radioactivity: "no",
        oxidation: "-1, 1",
        atomicradius: "120",
        electronegativity: "2.20",
        ionization: "13.598",
        density: "0.0000899",
        melting: "14",
        boiling: "20",
        yeardiscovered: "1766",
        
        tablerow18col: 1,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Helium",
        atomicnumber: 2,
        symbol: "He",
        category: "Noble gas",
        atomicweight: "4.0026",
        atomicweightfull: "4.002602(2)",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 1,
        block: "s",
        
        electronconfig: "1s2",
        radioactivity: "no",
        oxidation: "n/a",
        atomicradius: "140",
        electronegativity: "n/a",
        ionization: "24.587",
        density: "0.0001785",
        melting: "1",
        boiling: "4",
        yeardiscovered: "1868",

        tablerow18col: 1,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Lithium",
        atomicnumber: 3,
        symbol: "Li",
        category: "Alkali metal",
        atomicweight: "6.94",
        atomicweightfull: "[6.938, 6.997]",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 2,
        block: "s",
        
        electronconfig: "[He] 2s1",
        radioactivity: "no",
        oxidation: "1",
        atomicradius: "182",
        electronegativity: "0.98",
        ionization: "5.392",
        density: "0.535",
        melting: "454",
        boiling: "1615",
        yeardiscovered: "1817",
        
        
        tablerow18col: 2,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Beryllium",
        atomicnumber: 4,
        symbol: "Be",
        category: "Alkaline earth metal",
        atomicweight: "9.0122",
        atomicweightfull: "9.0121831(5)",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 2,
        block: "s",
        
        
        electronconfig: "[He] 2s2",
        radioactivity: "no",
        oxidation: "2",
        atomicradius: "153",
        electronegativity: "1.57",
        ionization: "9.323",
        density: "1.848",
        melting: "1560",
        boiling: "2743",
        yeardiscovered: "1798",
        
        tablerow18col: 2,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Boron",
        atomicnumber: 5,
        symbol: "B",
        category: "Metalloid",
        atomicweight: "10.81",
        atomicweightfull: "[10.806, 10.821]",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 2,
        block: "p",
        
        electronconfig: "[He] 2s2 2p1",
        radioactivity: "no",
        oxidation: "1, 2, 3",
        atomicradius: "192",
        electronegativity: "2.04",
        ionization: "8.298",
        density: "2.37",
        melting: "2348",
        boiling: "4273",
        yeardiscovered: "1807",
        
        tablerow18col: 2,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Carbon",
        atomicnumber: 6,
        symbol: "C",
        category: "Reactive nonmetal",
        atomicweight: "12.011",
        atomicweightfull: "[12.0096, 12.0116]",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 2,
        block: "p",

        electronconfig: "[He] 2s2 2p2",
        radioactivity: "no",
        oxidation: "-4, -3, -2, -1, 1, 2, 3, 4",
        atomicradius: "170",
        electronegativity: "2.55",
        ionization: "11.260",
        density: "2.26",
        melting: "3823",
        boiling: "4300",
        yeardiscovered: "Ancient",
        
        tablerow18col: 2,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Nitrogen",
        atomicnumber: 7,
        symbol: "N",
        category: "Reactive nonmetal",
        atomicweight: "14.007",
        atomicweightfull: "[14.00643, 14.00728]",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 15,
        period: 2,
        block: "p",
        
        electronconfig: "[He] 2s2 2p3",
        radioactivity: "no",
        oxidation: "-3, -2, -1, 1, 2, 3, 4, 5",
        atomicradius: "155",
        electronegativity: "3.04",
        ionization: "14.534",
        density: "0.001251",
        melting: "63",
        boiling: "77",
        yeardiscovered: "1772",
        
        tablerow18col: 2,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Oxygen",
        atomicnumber: 8,
        symbol: "O",
        category: "Reactive nonmetal",
        atomicweight: "15.999",
        atomicweightfull: "[15.99903, 15.99977]",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 16,
        period: 2,
        block: "p",
        
        electronconfig: "[He] 2s2 2p4",
        radioactivity: "no",
        oxidation: "-2, -1, 1, 2",
        atomicradius: "152",
        electronegativity: "3.44",
        ionization: "13.618",
        density: "0.001429",
        melting: "55",
        boiling: "90",
        yeardiscovered: "1774",
        
        tablerow18col: 2,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Fluorine",
        atomicnumber: 9,
        symbol: "F",
        category: "Reactive nonmetal",
        atomicweight: "18.998",
        atomicweightfull: "18.998403163(6)",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 17,
        period: 2,
        block: "p",
        
        electronconfig: "[He] 2s2 2p5",
        radioactivity: "no",
        oxidation: "-1",
        atomicradius: "147",
        electronegativity: "3.98",
        ionization: "17.423",
        density: "0.001696",
        melting: "54",
        boiling: "85",
        yeardiscovered: "1670",
        
        tablerow18col: 2,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Neon",
        atomicnumber: 10,
        symbol: "Ne",
        category: "Noble gas",
        atomicweight: "20.18",
        atomicweightfull: "20.1797(6)",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 2,
        block: "p",
       
        electronconfig: "[He] 2s2 2p6",
        radioactivity: "no",
        oxidation: "n/a",
        atomicradius: "154",
        electronegativity: "n/a",
        ionization: "21.565",
        density: "0.0009",
        melting: "25",
        boiling: "27",
        yeardiscovered: "1898",
       
        tablerow18col: 2,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Sodium",
        atomicnumber: 11,
        symbol: "Na",
        category: "Alkali metal",
        atomicweight: "22.99",
        atomicweightfull: "22.98976928(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 3,
        block: "s",
        
        electronconfig: "[Ne] 3s1",
        radioactivity: "no",
        oxidation: "-1, 1",
        atomicradius: "227",
        electronegativity: "0.93",
        ionization: "5.139",
        density: "0.968",
        melting: "371",
        boiling: "1156",
        yeardiscovered: "1807",
        
        tablerow18col: 3,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Magnesium",
        atomicnumber: 12,
        symbol: "Mg",
        category: "Alkaline earth metal",
        atomicweight: "24.305",
        atomicweightfull: "[24.304, 24.307] ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 3,
        block: "s",
        
        electronconfig: "[Ne] 3s2",
        radioactivity: "no",
        oxidation: "1, 2",
        atomicradius: "173",
        electronegativity: "1.31",
        ionization: "7.646",
        density: "1.738",
        melting: "923",
        boiling: "1363",
        yeardiscovered: "1808",
        
        tablerow18col: 3,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Aluminium",
        atomicnumber: 13,
        symbol: "Al",
        category: "Post-transition metal",
        atomicweight: "26.982",
        atomicweightfull: "26.9815384(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 3,
        block: "p",
        
        electronconfig: "[Ne] 3s2 3p1",
        radioactivity: "no",
        oxidation: "1, 3",
        atomicradius: "184",
        electronegativity: "1.61",
        ionization: "5.986",
        density: "2.7",
        melting: "933",
        boiling: "2792",
        yeardiscovered: "Ancient",
        
        tablerow18col: 3,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Silicon",
        atomicnumber: 14,
        symbol: "Si",
        category: "Metalloid",
        atomicweight: "28.085",
        atomicweightfull: "[28.084, 28.086] ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 3,
        block: "p",
        
        electronconfig: "[Ne] 3s2 3p2",
        radioactivity: "no",
        oxidation: "-4, -3, -2, -1, 1, 2, 3, 4",
        atomicradius: "210",
        electronegativity: "1.90",
        ionization: "8.152",
        density: "2.33",
        melting: "1687",
        boiling: "3173",
        yeardiscovered: "1854",
        
        tablerow18col: 3,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Phosphorus",
        atomicnumber: 15,
        symbol: "P",
        category: "Reactive nonmetal",
        atomicweight: "30.974",
        atomicweightfull: "30.973761998(5) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 15,
        period: 3,
        block: "p",
        
        electronconfig: "[Ne] 3s2 3p3",
        radioactivity: "no",
        oxidation: "-3, -2, -1, 1, 2, 3, 4, 5",
        atomicradius: "180",
        electronegativity: "2.19",
        ionization: "10.487",
        density: "1.823",
        melting: "317",
        boiling: "554",
        yeardiscovered: "1669",
        
        tablerow18col: 3,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Sulfur",
        atomicnumber: 16,
        symbol: "S",
        category: "Reactive nonmetal",
        atomicweight: "32.06",
        atomicweightfull: "[32.059, 32.076] ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 16,
        period: 3,
        block: "p",
        
        electronconfig: "[Ne] 3s2 3p4",
        radioactivity: "no",
        oxidation: "-2, -1, 1, 2, 3, 4, 5, 6",
        atomicradius: "180",
        electronegativity: "2.58",
        ionization: "10.360",
        density: "1.96",
        melting: "388",
        boiling: "718",
        yeardiscovered: "Ancient",
        
        tablerow18col: 3,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Chlorine",
        atomicnumber: 17,
        symbol: "Cl",
        category: "Reactive nonmetal",
        atomicweight: "35.45",
        atomicweightfull: "[35.446, 35.457] ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 17,
        period: 3,
        block: "p",
        
        electronconfig: "[Ne] 3s2 3p5",
        radioactivity: "no",
        oxidation: "-1, 1, 2, 3, 4, 5, 6, 7",
        atomicradius: "175",
        electronegativity: "3.16",
        ionization: "12.968",
        density: "0.003214",
        melting: "172",
        boiling: "239",
        yeardiscovered: "1774",
        
        tablerow18col: 3,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Argon",
        atomicnumber: 18,
        symbol: "Ar",
        category: "Noble gas",
        atomicweight: "39.95",
        atomicweightfull: "[39.792, 39.963] ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 3,
        block: "p",
        
        electronconfig: "[Ne] 3s2 3p6",
        radioactivity: "no",
        oxidation: "n/a",
        atomicradius: "188",
        electronegativity: "n/a",
        ionization: "15.760",
        density: "0.001784",
        melting: "84",
        boiling: "87",
        yeardiscovered: "1894",
        
        tablerow18col: 3,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Potassium",
        atomicnumber: 19,
        symbol: "K",
        category: "Alkali metal",
        atomicweight: "39.098",
        atomicweightfull: "39.0983(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 4,
        block: "s",
        
        electronconfig: "[Ar] 4s1",
        radioactivity: "no",
        oxidation: "1",
        atomicradius: "275",
        electronegativity: "0.82",
        ionization: "4.341",
        density: "0.856",
        melting: "337",
        boiling: "1032",
        yeardiscovered: "1807",
        
        tablerow18col: 4,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Calcium",
        atomicnumber: 20,
        symbol: "Ca",
        category: "Alkaline earth metal",
        atomicweight: "40.078",
        atomicweightfull: "40.078(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 4,
        block: "s",
        
        electronconfig: "[Ar] 4s2",
        radioactivity: "no",
        oxidation: "2",
        atomicradius: "231",
        electronegativity: "1.00",
        ionization: "6.113",
        density: "1.55",
        melting: "1115",
        boiling: "1757",
        yeardiscovered: "Ancient",
        
        tablerow18col: 4,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Scandium",
        atomicnumber: 21,
        symbol: "Sc",
        category: "Transition metal",
        atomicweight: "44.956",
        atomicweightfull: "44.955908(5) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 3,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d1 4s2",
        radioactivity: "no",
        oxidation: "1, 2, 3",
        atomicradius: "211",
        electronegativity: "1.36",
        ionization: "6.562",
        density: "2.985",
        melting: "1814",
        boiling: "3103",
        yeardiscovered: "1876",
        
        tablerow18col: 4,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Titanium",
        atomicnumber: 22,
        symbol: "Ti",
        category: "Transition metal",
        atomicweight: "47.867",
        atomicweightfull: "47.867(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 4,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d2 4s2",
        radioactivity: "no",
        oxidation: "-1, 2, 3, 4",
        atomicradius: "187",
        electronegativity: "1.54",
        ionization: "6.828",
        density: "4.507",
        melting: "1941",
        boiling: "3560",
        yeardiscovered: "1791",
        
        tablerow18col: 4,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Vanadium",
        atomicnumber: 23,
        symbol: "V",
        category: "Transition metal",
        atomicweight: "50.942",
        atomicweightfull: "50.9415(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 5,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d3 4s2",
        radioactivity: "no",
        oxidation: "-1, 2, 3, 4",
        atomicradius: "179",
        electronegativity: "1.63",
        ionization: "6.746",
        density: "6.11",
        melting: "2183",
        boiling: "3680",
        yeardiscovered: "1803",
        
        tablerow18col: 4,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Chromium",
        atomicnumber: 24,
        symbol: "Cr",
        category: "Transition metal",
        atomicweight: "51.996",
        atomicweightfull: "51.9961(6) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 6,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d5 4s1",
        radioactivity: "no",
        oxidation: "-2, -1, 1, 2, 3, 4, 5, 6",
        atomicradius: "189",
        electronegativity: "1.66",
        ionization: "6.767",
        density: "7.14",
        melting: "2180",
        boiling: "2944",
        yeardiscovered: "Ancient",
        
        tablerow18col: 4,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Manganese",
        atomicnumber: 25,
        symbol: "Mn",
        category: "Transition metal",
        atomicweight: "54.938",
        atomicweightfull: "54.938043(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 7,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d5 4s2",
        radioactivity: "no",
        oxidation: "-3, -2, -1, 1, 2, 3, 4, 5, 6, 7",
        atomicradius: "197",
        electronegativity: "1.55",
        ionization: "7.434",
        density: "7.47",
        melting: "1519",
        boiling: "2334",
        yeardiscovered: "1774",
        
        tablerow18col: 4,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Iron",
        atomicnumber: 26,
        symbol: "Fe",
        category: "Transition metal",
        atomicweight: "55.845",
        atomicweightfull: "55.845(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 8,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d6 4s2",
        radioactivity: "no",
        oxidation: "-2, -1, 1, 2, 3, 4, 5, 6",
        atomicradius: "194",
        electronegativity: "1.83",
        ionization: "7.902",
        density: "7.874",
        melting: "1811",
        boiling: "3134",
        yeardiscovered: "Ancient",
        
        tablerow18col: 4,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Cobalt",
        atomicnumber: 27,
        symbol: "Co",
        category: "Transition metal",
        atomicweight: "58.933",
        atomicweightfull: "58.933194(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 9,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d7 4s2",
        radioactivity: "no",
        oxidation: "-1, 1, 2, 3, 4, 5",
        atomicradius: "192",
        electronegativity: "1.88",
        ionization: "7.881",
        density: "8.9",
        melting: "1768",
        boiling: "3200",
        yeardiscovered: "Ancient",

        tablerow18col: 4,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Nickel",
        atomicnumber: 28,
        symbol: "Ni",
        category: "Transition metal",
        atomicweight: "58.693",
        atomicweightfull: "58.6934(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 10,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d8 4s2",
        radioactivity: "no",
        oxidation: "-1, 1, 2, 3, 4",
        atomicradius: "163",
        electronegativity: "1.91",
        ionization: "7.640",
        density: "8.908",
        melting: "1728",
        boiling: "3186",
        yeardiscovered: "1751",
        
        tablerow18col: 4,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Copper",
        atomicnumber: 29,
        symbol: "Cu",
        category: "Transition metal",
        atomicweight: "63.546",
        atomicweightfull: "63.546(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 11,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d10 4s1",
        radioactivity: "no",
        oxidation: "1, 2, 3, 4",
        atomicradius: "140",
        electronegativity: "1.90",
        ionization: "7.726",
        density: "8.92",
        melting: "1358",
        boiling: "3200",
        yeardiscovered: "Ancient",
        
        tablerow18col: 4,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Zinc",
        atomicnumber: 30,
        symbol: "Zn",
        category: "Post-transition metal",
        atomicweight: "65.38",
        atomicweightfull: "65.38(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 12,
        period: 4,
        block: "d",
        
        electronconfig: "[Ar] 3d10 4s2",
        radioactivity: "no",
        oxidation: "2",
        atomicradius: "139",
        electronegativity: "1.65",
        ionization: "9.394",
        density: "7.14",
        melting: "693",
        boiling: "1180",
        yeardiscovered: "1746",
        
        tablerow18col: 4,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Gallium",
        atomicnumber: 31,
        symbol: "Ga",
        category: "Post-transition metal",
        atomicweight: "69.723",
        atomicweightfull: "69.723(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 4,
        block: "p",
        
        electronconfig: "[Ar] 3d10 4s2 4p1",
        radioactivity: "no",
        oxidation: "1, 2, 3",
        atomicradius: "187",
        electronegativity: "1.81",
        ionization: "5.999",
        density: "5.904",
        melting: "303",
        boiling: "2477",
        yeardiscovered: "1875",
        
        tablerow18col: 4,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Germanium",
        atomicnumber: 32,
        symbol: "Ge",
        category: "Metalloid",
        atomicweight: "72.63",
        atomicweightfull: "72.630(8) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 4,
        block: "p",
        
        electronconfig: "[Ar] 3d10 4s2 4p2",
        radioactivity: "no",
        oxidation: "-4, 1, 2, 3, 4",
        atomicradius: "211",
        electronegativity: "2.01",
        ionization: "7.899",
        density: "5.323",
        melting: "1211",
        boiling: "3093",
        yeardiscovered: "1886",
        
        tablerow18col: 4,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Arsenic",
        atomicnumber: 33,
        symbol: "As",
        category: "Metalloid",
        atomicweight: "74.922",
        atomicweightfull: "74.921595(6) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 15,
        period: 4,
        block: "p",
        
        electronconfig: "[Ar] 3d10 4s2 4p3",
        radioactivity: "no",
        oxidation: "-3, 2, 3, 5",
        atomicradius: "185",
        electronegativity: "2.18",
        ionization: "9.789",
        density: "5.727",
        melting: "1090",
        boiling: "887",
        yeardiscovered: "Ancient",
        
        tablerow18col: 4,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Selenium",
        atomicnumber: 34,
        symbol: "Se",
        category: "Reactive nonmetal",
        atomicweight: "78.971",
        atomicweightfull: "78.971(8) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 16,
        period: 4,
        block: "p",
        
        electronconfig: "[Ar] 3d10 4s2 4p4",
        radioactivity: "no",
        oxidation: "-2, 2, 4, 6",
        atomicradius: "190",
        electronegativity: "2.55",
        ionization: "9.752",
        density: "4.819",
        melting: "494",
        boiling: "958",
        yeardiscovered: "1817",
        
        tablerow18col: 4,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Bromine",
        atomicnumber: 35,
        symbol: "Br",
        category: "Reactive nonmetal",
        atomicweight: "79.904",
        atomicweightfull: "[79.901, 79.907] ",
        occurrence: "Liquid",
        stateofmatter: "Primordial",
        group: 17,
        period: 4,
        block: "p",
        
        electronconfig: "[Ar] 3d10 4s2 4p5",
        radioactivity: "no",
        oxidation: "-1, 1, 3, 4, 5, 7",
        atomicradius: "185",
        electronegativity: "2.96",
        ionization: "11.814",
        density: "3.12",
        melting: "266",
        boiling: "332",
        yeardiscovered: "1826",
        
        tablerow18col: 4,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Krypton",
        atomicnumber: 36,
        symbol: "Kr",
        category: "Noble gas",
        atomicweight: "83.798",
        atomicweightfull: "83.798(2) ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 4,
        block: "p",
        
        electronconfig: "[Ar] 3d10 4s2 4p6",
        radioactivity: "no",
        oxidation: "2",
        atomicradius: "202",
        electronegativity: "3.00",
        ionization: "14.000",
        density: "0.00375",
        melting: "116",
        boiling: "120",
        yeardiscovered: "1898",
        
        tablerow18col: 4,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Rubidium",
        atomicnumber: 37,
        symbol: "Rb",
        category: "Alkali metal",
        atomicweight: "85.468",
        atomicweightfull: "85.4678(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 5,
        block: "s",
        
        electronconfig: "[Kr] 5s1",
        radioactivity: "no",
        oxidation: "1",
        atomicradius: "303",
        electronegativity: "0.82",
        ionization: "14.177",
        density: "1.532",
        melting: "312",
        boiling: "961",
        yeardiscovered: "1861",
        
        tablerow18col: 5,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Strontium",
        atomicnumber: 38,
        symbol: "Sr",
        category: "Alkaline earth metal",
        atomicweight: "87.62",
        atomicweightfull: "87.62(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 5,
        block: "s",
        
        electronconfig: "[Kr] 5s2",
        radioactivity: "no",
        oxidation: "2",
        atomicradius: "249",
        electronegativity: "0.95",
        ionization: "5.695",
        density: "2.63",
        melting: "1050",
        boiling: "1655",
        yeardiscovered: "1790",
        
        tablerow18col: 5,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Yttrium",
        atomicnumber: 39,
        symbol: "Y",
        category: "Transition metal",
        atomicweight: "88.906",
        atomicweightfull: "88.90584(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 3,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d1 5s2",
        radioactivity: "no",
        oxidation: "1, 2, 3",
        atomicradius: "219",
        electronegativity: "1.22",
        ionization: "6.217",
        density: "4.472",
        melting: "1799",
        boiling: "3618",
        yeardiscovered: "1794",
        
        tablerow18col: 5,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Zirconium",
        atomicnumber: 40,
        symbol: "Zr",
        category: "Transition metal",
        atomicweight: "91.224",
        atomicweightfull: "91.224(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 4,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d2 5s2",
        radioactivity: "no",
        oxidation: "1, 2, 3, 4",
        atomicradius: "186",
        electronegativity: "1.33",
        ionization: "6.634",
        density: "6.511",
        melting: "2128",
        boiling: "4682",
        yeardiscovered: "1789",
        
        tablerow18col: 5,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Niobium",
        atomicnumber: 41,
        symbol: "Nb",
        category: "Transition metal",
        atomicweight: "92.906",
        atomicweightfull: "92.90637(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 5,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d4 5s1",
        radioactivity: "no",
        oxidation: "-1, 2, 3, 4, 5",
        atomicradius: "207",
        electronegativity: "1.60",
        ionization: "6.759",
        density: "8.57",
        melting: "2750",
        boiling: "5017",
        yeardiscovered: "1801",
        
        tablerow18col: 5,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Molybdenum",
        atomicnumber: 42,
        symbol: "Mo",
        category: "Transition metal",
        atomicweight: "95.95",
        atomicweightfull: "95.95(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 6,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d5 5s1",
        radioactivity: "no",
        oxidation: "-2, -1, 1, 2, 3, 4, 5, 6",
        atomicradius: "209",
        electronegativity: "2.16",
        ionization: "7.092",
        density: "10.28",
        melting: "2896",
        boiling: "4912",
        yeardiscovered: "1778",
        
        tablerow18col: 5,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Technetium",
        atomicnumber: 43,
        symbol: "Tc",
        category: "Transition metal",
        atomicweight: "[97]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 7,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d5 5s2",
        radioactivity: "yes",
        oxidation: "-3, -1, 1, 2, 3, 4, 5, 6, 7",
        atomicradius: "207",
        electronegativity: "1.90",
        ionization: "7.280",
        density: "11.5",
        melting: "2430",
        boiling: "4538",
        yeardiscovered: "1937",
        
        tablerow18col: 5,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Ruthenium",
        atomicnumber: 44,
        symbol: "Ru",
        category: "Transition metal",
        atomicweight: "101.07",
        atomicweightfull: "101.07(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 8,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d7 5s1",
        radioactivity: "no",
        oxidation: "-2, 1, 2, 3, 4, 5, 6, 7, 8",
        atomicradius: "195",
        electronegativity: "2.20",
        ionization: "7.361",
        density: "12.37",
        melting: "2607",
        boiling: "4423",
        yeardiscovered: "1827",
        
        tablerow18col: 5,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Rhodium",
        atomicnumber: 45,
        symbol: "Rh",
        category: "Transition metal",
        atomicweight: "102.91",
        atomicweightfull: "102.90549(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 9,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d8 5s1",
        radioactivity: "no",
        oxidation: "-1, 1, 2, 3, 4, 5, 6",
        atomicradius: "202",
        electronegativity: "2.28",
        ionization: "7.459",
        density: "12.45",
        melting: "2237",
        boiling: "3968",
        yeardiscovered: "1803",
        
        tablerow18col: 5,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Palladium",
        atomicnumber: 46,
        symbol: "Pd",
        category: "Transition metal",
        atomicweight: "106.42",
        atomicweightfull: "106.42(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 10,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d10",
        radioactivity: "no",
        oxidation: "2, 4",
        atomicradius: "163",
        electronegativity: "2.20",
        ionization: "8.337",
        density: "12.023",
        melting: "1828",
        boiling: "3236",
        yeardiscovered: "1803",
        
        tablerow18col: 5,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Silver",
        atomicnumber: 47,
        symbol: "Ag",
        category: "Transition metal",
        atomicweight: "107.87",
        atomicweightfull: "107.8682(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 11,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d10 5s1",
        radioactivity: "no",
        oxidation: "1, 2, 3",
        atomicradius: "172",
        electronegativity: "1.93",
        ionization: "7.576",
        density: "10.49",
        melting: "1235",
        boiling: "2435",
        yeardiscovered: "Ancient",
        
        tablerow18col: 5,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Cadmium",
        atomicnumber: 48,
        symbol: "Cd",
        category: "Post-transition metal",
        atomicweight: "112.41",
        atomicweightfull: "112.414(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 12,
        period: 5,
        block: "d",
        
        electronconfig: "[Kr] 4d10 5s2",
        radioactivity: "no",
        oxidation: "2",
        atomicradius: "158",
        electronegativity: "1.69",
        ionization: "8.994",
        density: "8.65",
        melting: "594",
        boiling: "1040",
        yeardiscovered: "1817",
        
        tablerow18col: 5,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Indium",
        atomicnumber: 49,
        symbol: "In",
        category: "Post-transition metal",
        atomicweight: "114.82",
        atomicweightfull: "114.818(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 5,
        block: "p",
        
        electronconfig: "[Kr] 4d10 5s2 5p1",
        radioactivity: "no",
        oxidation: "1, 2, 3",
        atomicradius: "193",
        electronegativity: "1.78",
        ionization: "5.786",
        density: "7.31",
        melting: "430",
        boiling: "2345",
        yeardiscovered: "1863",
        
        tablerow18col: 5,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Tin",
        atomicnumber: 50,
        symbol: "Sn",
        category: "Post-transition metal",
        atomicweight: "118.71",
        atomicweightfull: "118.710(7) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 5,
        block: "p",
        
        electronconfig: "[Kr] 4d10 5s2 5p2",
        radioactivity: "no",
        oxidation: "-4, 2, 4",
        atomicradius: "217",
        electronegativity: "1.96",
        ionization: "7.344",
        density: "7.31",
        melting: "505",
        boiling: "2875",
        yeardiscovered: "Ancient",

        tablerow18col: 5,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Antimony",
        atomicnumber: 51,
        symbol: "Sb",
        category: "Metalloid",
        atomicweight: "121.76",
        atomicweightfull: "121.760(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 15,
        period: 5,
        block: "p",
        
        electronconfig: "[Kr] 4d10 5s2 5p3",
        radioactivity: "no",
        oxidation: "-3, 3, 5",
        atomicradius: "206",
        electronegativity: "2.05",
        ionization: "8.608",
        density: "6.697",
        melting: "904",
        boiling: "1860",
        yeardiscovered: "Ancient",
        
        tablerow18col: 5,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Tellurium",
        atomicnumber: 52,
        symbol: "Te",
        category: "Metalloid",
        atomicweight: "127.6",
        atomicweightfull: "127.60(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 16,
        period: 5,
        block: "p",
        
        electronconfig: "[Kr] 4d10 5s2 5p4",
        radioactivity: "no",
        oxidation: "-2, 2, 4, 5, 6",
        atomicradius: "206",
        electronegativity: "2.10",
        ionization: "9.010",
        density: "6.24",
        melting: "723",
        boiling: "1261",
        yeardiscovered: "1782",
        
        tablerow18col: 5,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Iodine",
        atomicnumber: 53,
        symbol: "I",
        category: "Reactive nonmetal",
        atomicweight: "126.9",
        atomicweightfull: "126.90447(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 17,
        period: 5,
        block: "p",
        
        electronconfig: "[Kr] 4d10 5s2 5p5",
        radioactivity: "no",
        oxidation: "-1, 1, 3, 5, 7",
        atomicradius: "198",
        electronegativity: "2.66",
        ionization: "10.451",
        density: "4.94",
        melting: "387",
        boiling: "457",
        yeardiscovered: "1811",
        
        tablerow18col: 5,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Xenon",
        atomicnumber: 54,
        symbol: "Xe",
        category: "Noble gas",
        atomicweight: "131.29",
        atomicweightfull: "131.293(6) ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 5,
        block: "p",
        
        electronconfig: "[Kr] 4d10 5s2 5p6",
        radioactivity: "no",
        oxidation: "2, 4, 6, 8",
        atomicradius: "216",
        electronegativity: "2.60",
        ionization: "12.130",
        density: "0.0059",
        melting: "161",
        boiling: "165",
        yeardiscovered: "1898",
        
        tablerow18col: 5,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Caesium",
        atomicnumber: 55,
        symbol: "Cs",
        category: "Alkali metal",
        atomicweight: "132.91",
        atomicweightfull: "132.90545196(6) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 6,
        block: "s",
        
        electronconfig: "[Xe] 6s1",
        radioactivity: "no",
        oxidation: "1",
        atomicradius: "343",
        electronegativity: "0.79",
        ionization: "3.894",
        density: "1.879",
        melting: "302",
        boiling: "944",
        yeardiscovered: "1860",
        
        tablerow18col: 6,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Barium",
        atomicnumber: 56,
        symbol: "Ba",
        category: "Alkaline earth metal",
        atomicweight: "137.33",
        atomicweightfull: "137.327(7) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 6,
        block: "s",
        
        electronconfig: "[Xe] 6s2",
        radioactivity: "no",
        oxidation: "2",
        atomicradius: "268",
        electronegativity: "0.89",
        ionization: "5.212",
        density: "3.51",
        melting: "1000",
        boiling: "2143",
        yeardiscovered: "1808",
        
        tablerow18col: 6,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Lanthanum",
        atomicnumber: 57,
        symbol: "La",
        category: "Lanthanide",
        atomicweight: "138.91",
        atomicweightfull: "138.90547(7) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 3,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 5d1 6s2",
        radioactivity: "no",
        oxidation: "2, 3",
        atomicradius: "240",
        electronegativity: "1.10",
        ionization: "5.577",
        density: "6.146",
        melting: "1193",
        boiling: "3737",
        yeardiscovered: "1839",
        
        tablerow18col: 6,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Cerium",
        atomicnumber: 58,
        symbol: "Ce",
        category: "Lanthanide",
        atomicweight: "140.12",
        atomicweightfull: "140.116(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f1 5d1 6s2",
        radioactivity: "no",
        oxidation: "2, 3, 4",
        atomicradius: "235",
        electronegativity: "1.12",
        ionization: "5.539",
        density: "6.689",
        melting: "1071",
        boiling: "3633",
        yeardiscovered: "1803",
        
        tablerow18col: 8,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Praseodymium",
        atomicnumber: 59,
        symbol: "Pr",
        category: "Lanthanide",
        atomicweight: "140.91",
        atomicweightfull: "140.90766(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f3 6s2",
        radioactivity: "no",
        oxidation: "2, 3, 4",
        atomicradius: "239",
        electronegativity: "1.13",
        ionization: "5.473",
        density: "6.64",
        melting: "1204",
        boiling: "3563",
        yeardiscovered: "1885",
        
        tablerow18col: 8,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Neodymium",
        atomicnumber: 60,
        symbol: "Nd",
        category: "Lanthanide",
        atomicweight: "144.24",
        atomicweightfull: "144.242(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f4 6s2",
        radioactivity: "no",
        oxidation: "2, 3",
        atomicradius: "229",
        electronegativity: "1.14",
        ionization: "5.525",
        density: "7.01",
        melting: "1294",
        boiling: "3373",
        yeardiscovered: "1885",
        
        tablerow18col: 8,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Promethium",
        atomicnumber: 61,
        symbol: "Pm",
        category: "Lanthanide",
        atomicweight: "[145]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f5 6s2",
        radioactivity: "yes",
        oxidation: "3",
        atomicradius: "236",
        electronegativity: "1.13",
        ionization: "5.582",
        density: "7.264",
        melting: "1373",
        boiling: "3273",
        yeardiscovered: "1947",
        
        tablerow18col: 8,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Samarium",
        atomicnumber: 62,
        symbol: "Sm",
        category: "Lanthanide",
        atomicweight: "150.36",
        atomicweightfull: "150.36(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f6 6s2",
        radioactivity: "no",
        oxidation: "2, 3",
        atomicradius: "229",
        electronegativity: "1.17",
        ionization: "5.644",
        density: "7.353",
        melting: "1345",
        boiling: "2076",
        yeardiscovered: "1853",
        
        tablerow18col: 8,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Europium",
        atomicnumber: 63,
        symbol: "Eu",
        category: "Lanthanide",
        atomicweight: "151.96",
        atomicweightfull: "151.964(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f7 6s2",
        radioactivity: "no",
        oxidation: "2, 3",
        atomicradius: "233",
        electronegativity: "1.20",
        ionization: "5.670",
        density: "5.244",
        melting: "1095",
        boiling: "1800",
        yeardiscovered: "1901",
        
        tablerow18col: 8,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Gadolinium",
        atomicnumber: 64,
        symbol: "Gd",
        category: "Lanthanide",
        atomicweight: "157.25",
        atomicweightfull: "157.25(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f7 5d1 6s2",
        radioactivity: "no",
        oxidation: "1, 2, 3",
        atomicradius: "237",
        electronegativity: "1.20",
        ionization: "6.150",
        density: "7.901",
        melting: "1586",
        boiling: "3523",
        yeardiscovered: "1880",
        
        tablerow18col: 8,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Terbium",
        atomicnumber: 65,
        symbol: "Tb",
        category: "Lanthanide",
        atomicweight: "158.93",
        atomicweightfull: "158.925354(8) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f9 6s2",
        radioactivity: "no",
        oxidation: "1, 3, 4",
        atomicradius: "221",
        electronegativity: "1.20",
        ionization: "5.864",
        density: "8.219",
        melting: "1629",
        boiling: "3503",
        yeardiscovered: "1843",
        
        tablerow18col: 8,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Dysprosium",
        atomicnumber: 66,
        symbol: "Dy",
        category: "Lanthanide",
        atomicweight: "162.5",
        atomicweightfull: "162.500(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f10 6s2",
        radioactivity: "no",
        oxidation: "2, 3",
        atomicradius: "229",
        electronegativity: "1.22",
        ionization: "5.939",
        density: "8.551",
        melting: "1685",
        boiling: "2840",
        yeardiscovered: "1886",
        
        tablerow18col: 8,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Holmium",
        atomicnumber: 67,
        symbol: "Ho",
        category: "Lanthanide",
        atomicweight: "164.93",
        atomicweightfull: "164.930328(7) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f11 6s2",
        radioactivity: "no",
        oxidation: "3",
        atomicradius: "216",
        electronegativity: "1.23",
        ionization: "6.022",
        density: "8.795",
        melting: "1747",
        boiling: "2973",
        yeardiscovered: "1878",
        
        tablerow18col: 8,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Erbium",
        atomicnumber: 68,
        symbol: "Er",
        category: "Lanthanide",
        atomicweight: "167.26",
        atomicweightfull: "167.259(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f12 6s2",
        radioactivity: "no",
        oxidation: "3",
        atomicradius: "235",
        electronegativity: "1.24",
        ionization: "6.108",
        density: "9.066",
        melting: "1770",
        boiling: "3141",
        yeardiscovered: "1842",
        
        tablerow18col: 8,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Thulium",
        atomicnumber: 69,
        symbol: "Tm",
        category: "Lanthanide",
        atomicweight: "168.93",
        atomicweightfull: "168.934218(6) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f13 6s2",
        radioactivity: "no",
        oxidation: "2, 3",
        atomicradius: "227",
        electronegativity: "1.25",
        ionization: "6.184",
        density: "9.321",
        melting: "1818",
        boiling: "2223",
        yeardiscovered: "1879",
        
        tablerow18col: 8,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Ytterbium",
        atomicnumber: 70,
        symbol: "Yb",
        category: "Lanthanide",
        atomicweight: "173.05",
        atomicweightfull: "173.045(10) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f14 6s2",
        radioactivity: "no",
        oxidation: "2, 3",
        atomicradius: "242",
        electronegativity: "1.10",
        ionization: "6.254",
        density: "6.57",
        melting: "1092",
        boiling: "1469",
        yeardiscovered: "1878",
        
        tablerow18col: 8,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Lutenium",
        atomicnumber: 71,
        symbol: "Lu",
        category: "Lanthanide",
        atomicweight: "174.97",
        atomicweightfull: "174.9668(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        
        electronconfig: "[Xe] 4f14 5d1 6s2",
        radioactivity: "no",
        oxidation: "3",
        atomicradius: "221",
        electronegativity: "1.27",
        ionization: "5.426",
        density: "9.841",
        melting: "1936",
        boiling: "3675",
        yeardiscovered: "1907",
        
        tablerow18col: 8,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Hafnium",
        atomicnumber: 72,
        symbol: "Hf",
        category: "Transition metal",
        atomicweight: "178.49",
        atomicweightfull: "178.49(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 4,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 4f14 5d2 6s2",
        radioactivity: "no",
        oxidation: "2, 3, 4",
        atomicradius: "212",
        electronegativity: "1.30",
        ionization: "6.825",
        density: "13.31",
        melting: "2506",
        boiling: "4876",
        yeardiscovered: "1923",
        
        tablerow18col: 6,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Tantalum",
        atomicnumber: 73,
        symbol: "Ta",
        category: "Transition metal",
        atomicweight: "180.95",
        atomicweightfull: "180.94788(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 5,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 4f14 5d3 6s2",
        radioactivity: "no",
        oxidation: "-1, 2, 3, 4, 5",
        atomicradius: "217",
        electronegativity: "1.50",
        ionization: "7.550",
        density: "16.65",
        melting: "3290",
        boiling: "5731",
        yeardiscovered: "1802",
        
        tablerow18col: 6,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Tungsten",
        atomicnumber: 74,
        symbol: "W",
        category: "Transition metal",
        atomicweight: "183.84",
        atomicweightfull: "183.84(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 6,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 4f14 5d4 6s2",
        radioactivity: "no",
        oxidation: "-2, -1, 1, 2, 3, 4, 5, 6",
        atomicradius: "210",
        electronegativity: "2.36",
        ionization: "7.864",
        density: "19.25",
        melting: "3695",
        boiling: "5828",
        yeardiscovered: "1783",
        
        tablerow18col: 6,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Rhenium",
        atomicnumber: 75,
        symbol: "Re",
        category: "Transition metal",
        atomicweight: "186.21",
        atomicweightfull: "186.207(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 7,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 4f14 5d5 6s2",
        radioactivity: "no",
        oxidation: "-3, -1, 1, 2, 3, 4, 5, 6, 7",
        atomicradius: "217",
        electronegativity: "1.90",
        ionization: "7.834",
        density: "21.02",
        melting: "3459",
        boiling: "5869",
        yeardiscovered: "1925",
        
        tablerow18col: 6,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Osmium",
        atomicnumber: 76,
        symbol: "Os",
        category: "Transition metal",
        atomicweight: "190.23",
        atomicweightfull: "190.23(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 8,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 4f14 5d6 6s2",
        radioactivity: "no",
        oxidation: "-2, -1, 1, 2, 3, 4, 5, 6, 7, 8",
        atomicradius: "216",
        electronegativity: "2.20",
        ionization: "8.438",
        density: "22.61",
        melting: "3306",
        boiling: "5285",
        yeardiscovered: "1803",
        
        tablerow18col: 6,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Iridium",
        atomicnumber: 77,
        symbol: "Ir",
        category: "Transition metal",
        atomicweight: "192.22",
        atomicweightfull: "192.217(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 9,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 4f14 5d7 6s2",
        radioactivity: "no",
        oxidation: "-3, -1, 1, 2, 3, 4, 5, 6",
        atomicradius: "202",
        electronegativity: "2.20",
        ionization: "8.967",
        density: "22.65",
        melting: "2739",
        boiling: "4701",
        yeardiscovered: "1803",

        tablerow18col: 6,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Platinum",
        atomicnumber: 78,
        symbol: "Pt",
        category: "Transition metal",
        atomicweight: "195.08",
        atomicweightfull: "195.084(9) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 10,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 4f14 5d9 6s1",
        radioactivity: "no",
        oxidation: "2, 4, 5, 6",
        atomicradius: "209",
        electronegativity: "2.28",
        ionization: "8.959",
        density: "21.09",
        melting: "2041",
        boiling: "4098",
        yeardiscovered: "Ancient",
        
        tablerow18col: 6,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Gold",
        atomicnumber: 79,
        symbol: "Au",
        category: "Transition metal",
        atomicweight: "196.97",
        atomicweightfull: "196.966570(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 11,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 4f14 5d10 6s1",
        radioactivity: "no",
        oxidation: "-1, 1, 2, 3, 5",
        atomicradius: "166",
        electronegativity: "2.54",
        ionization: "9.226",
        density: "19.3",
        melting: "1337",
        boiling: "3129",
        yeardiscovered: "Ancient",
        
        tablerow18col: 6,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Mercury",
        atomicnumber: 80,
        symbol: "Hg",
        category: "Post-transition metal",
        atomicweight: "200.59",
        atomicweightfull: "200.592(3) ",
        occurrence: "Liquid",
        stateofmatter: "Primordial",
        group: 12,
        period: 6,
        block: "d",
        
        electronconfig: "[Xe] 4f14 5d10 6s2",
        radioactivity: "no",
        oxidation: "1, 2, 4",
        atomicradius: "209",
        electronegativity: "2.00",
        ionization: "10.438",
        density: "13.534",
        melting: "234",
        boiling: "630",
        yeardiscovered: "Ancient",
        
        tablerow18col: 6,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Thallium",
        atomicnumber: 81,
        symbol: "Tl",
        category: "Post-transition metal",
        atomicweight: "204.38",
        atomicweightfull: "[204.382, 204.385] ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Lead",
        atomicnumber: 82,
        symbol: "Pb",
        category: "Post-transition metal",
        atomicweight: "207.2",
        atomicweightfull: "207.2(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Bismuth",
        atomicnumber: 83,
        symbol: "Bi",
        category: "Post-transition metal",
        atomicweight: "208.98",
        atomicweightfull: "208.98040(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 15,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Polonium",
        atomicnumber: 84,
        symbol: "Po",
        category: "Post-transition metal",
        atomicweight: "[209]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 16,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Astatine",
        atomicnumber: 85,
        symbol: "At",
        category: "Metalloid",
        atomicweight: "[210]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 17,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Radon",
        atomicnumber: 86,
        symbol: "Rn",
        category: "Noble gas",
        atomicweight: "[222]",
        atomicweightfull: "-",
        occurrence: "Gas",
        stateofmatter: "From decay",
        group: 18,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Francium",
        atomicnumber: 87,
        symbol: "Fr",
        category: "Alkali metal",
        atomicweight: "[223]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 1,
        period: 7,
        block: "s",
        tablerow18col: 7,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Radium",
        atomicnumber: 88,
        symbol: "Ra",
        category: "Alkaline earth metal",
        atomicweight: "[226]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 2,
        period: 7,
        block: "s",
        tablerow18col: 7,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Actinium",
        atomicnumber: 89,
        symbol: "Ac",
        category: "Actinide",
        atomicweight: "[227]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 3,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Thorium",
        atomicnumber: 90,
        symbol: "Th",
        category: "Actinide",
        atomicweight: "232.04",
        atomicweightfull: "232.0377(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Protactinium",
        atomicnumber: 91,
        symbol: "Pa",
        category: "Actinide",
        atomicweight: "231.04",
        atomicweightfull: "231.03588(1) ",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Uranium",
        atomicnumber: 92,
        symbol: "U",
        category: "Actinide",
        atomicweight: "238.03",
        atomicweightfull: "238.02891(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Neptunium",
        atomicnumber: 93,
        symbol: "Np",
        category: "Actinide",
        atomicweight: "[237]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Plutonium",
        atomicnumber: 94,
        symbol: "Pu",
        category: "Actinide",
        atomicweight: "[244]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Americium",
        atomicnumber: 95,
        symbol: "Am",
        category: "Actinide",
        atomicweight: "[243]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Curium",
        atomicnumber: 96,
        symbol: "Cm",
        category: "Actinide",
        atomicweight: "[247]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Berkelium",
        atomicnumber: 97,
        symbol: "Bk",
        category: "Actinide",
        atomicweight: "[247]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Californium",
        atomicnumber: 98,
        symbol: "Cf",
        category: "Actinide",
        atomicweight: "[251]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Einsteinium",
        atomicnumber: 99,
        symbol: "Es",
        category: "Actinide",
        atomicweight: "[252]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Fermium",
        atomicnumber: 100,
        symbol: "Fm",
        category: "Actinide",
        atomicweight: "[257]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Mendelevium",
        atomicnumber: 101,
        symbol: "Md",
        category: "Actinide",
        atomicweight: "[258]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Nobelium",
        atomicnumber: 102,
        symbol: "No",
        category: "Actinide",
        atomicweight: "[259]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Lawrencium",
        atomicnumber: 103,
        symbol: "Lr",
        category: "Actinide",
        atomicweight: "[266]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Rutherfordium",
        atomicnumber: 104,
        symbol: "Rf",
        category: "Transition metal",
        atomicweight: "[267]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 4,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Dubnium",
        atomicnumber: 105,
        symbol: "Db",
        category: "Transition metal",
        atomicweight: "[268]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 5,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Seaborgium",
        atomicnumber: 106,
        symbol: "Sg",
        category: "Transition metal",
        atomicweight: "[269]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 6,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Bohrium",
        atomicnumber: 107,
        symbol: "Bh",
        category: "Transition metal",
        atomicweight: "[270]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 7,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Hassium",
        atomicnumber: 108,
        symbol: "Hs",
        category: "Transition metal",
        atomicweight: "[269]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 8,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Meitnerium",
        atomicnumber: 109,
        symbol: "Mt",
        category: "Unknown",
        atomicweight: "[278]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 9,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Darmstadtium",
        atomicnumber: 110,
        symbol: "Ds",
        category: "Unknown",
        atomicweight: "[281]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 10,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Roentgenium",
        atomicnumber: 111,
        symbol: "Rg",
        category: "Unknown",
        atomicweight: "[282]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 11,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Copernicum",
        atomicnumber: 112,
        symbol: "Cn",
        category: "Post-transition metal",
        atomicweight: "[285]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 12,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Nihonium",
        atomicnumber: 113,
        symbol: "Nh",
        category: "Unknown",
        atomicweight: "[286]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 13,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Flerovium",
        atomicnumber: 114,
        symbol: "Fl",
        category: "Unknown",
        atomicweight: "[289]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 14,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Moscovium",
        atomicnumber: 115,
        symbol: "Mc",
        category: "Unknown",
        atomicweight: "[290]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 15,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Livermorium",
        atomicnumber: 116,
        symbol: "Lv",
        category: "Unknown",
        atomicweight: "[293]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 16,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Tennessine",
        atomicnumber: 117,
        symbol: "Ts",
        category: "Unknown",
        atomicweight: "[294]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 17,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Oganesson",
        atomicnumber: 118,
        symbol: "Og",
        category: "Unknown",
        atomicweight: "[294]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 18,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 18,
        visible: true
    },
]
